### ISSUE TITLE
Наполнить вакансии

### ISSUE THREAD

**Issue by emustafin** [emustafin/Career#31]

**Comment by emustafin** [comment]
Список табов (стримов):
- Backend (сюда пойдет джава)
- Архитектура
- Data Science 
- QA 
- Mobile 
- Frontend 
- SRE/DevOps 
- Analyst 
- Product/Project
- Другое (дизайн, юикс, сап и все остальное)

**Логистика**
https://docs.google.com/document/d/1TVUt1ZbAsv5MoMkJUwhQhzcNpbRe4kP7Wo9tk-j1FZ0/edit#

**B2R**
https://docs.google.com/document/d/1XOoZyyRJK1n6GKY04HxytZzm3haoXD3lft0VhYQ7dyk/edit#

**B2C**
https://docs.google.com/document/d/1D6MsSMkdqn4I17_VLWCuRd-1UdIg2YJZ4qWao4EJ2Y4/edit#heading=h.1etaeedca406

**Коммерция** https://docs.google.com/document/d/1gkLEn98PqgEygVZHgjPDi5WU2HuT9B9ioYYJYW6T0ZU/edit#heading=h.lqamt38r3wug

**ИТ**
https://docs.google.com/document/d/1fSDvdorf5wa-O_L_2ASAALcFtarIkiFHYMuVWBV8Bsw/edit#

**Финансы**
https://docs.google.com/document/d/1BGXCTa2dvM5Bpy3WGCdJ0B2kd4Bbcq0lhELk6F76x1I/edit#

**Comment by Mel-SON** [comment]
Список табов так и не понял честно говоря. заполнил пока как понял. если что править все можно в админке.
